### ISSUE TITLE
Crash on startup: java.lang.IllegalStateException: Splash thread

### ISSUE THREAD

**Issue by Xiaminou** [AlexIIL/BetterLoadingScreen#35] opened 2015-07-25 12:50 UTC
Forge: 1448
BLS: 1.3.8
Crash Report: http://pastebin.com/xxtizECE

Crashes as soon as it loads the better loading screen.

**Comment by AlexIIL** [comment] 2015-07-25 14:09
Try restarting minecraft, or give me a full log file please.

**Comment by Xiaminou** [comment] 2015-07-26 10:20
Full log: https://drive.google.com/open?id=0B090g8mHJkCWQjZudnJtOFp1MXM

**Comment by AlexIIL** [comment] 2015-07-26 10:32
Ok, that's strange. Can you try disabling the forge splash screen and trying again? (In your config directory there should be a forge loading screen related config file, change the enabled config setting to false)

**Comment by AlexIIL** [comment] 2015-07-26 10:41
Hang on, how did you disable better loading screen?

(Better loading screen sort of try's to disable forges loading screen, however it fails the first time, causing a crash. The second time minecraft starts up, forges loading screen has disabled itself (because it crashed last time) and better loading screen can be shown).

That could explain what is happening if you didn't properly disable BLS or something went wrong. Although the log file doesn't have any mention of BLS in the disabled version (which you said it was working in).

**Comment by Xiaminou** [comment] 2015-07-26 13:43
I disabled it via curse's launcher wihich just put .disabled at the end of the file's name.
The first one is definitly using BLS, which gives an issue, and the second one says it ignores BLS because unknown format (.disabled).

**Comment by AlexIIL** [comment] 2015-07-26 14:02
Ok, that's not meant to happen then. Can you go to "C:\Program Files (x86)\Minecraft\Curse\Instances\Genesis\config\" and open "splash.properties" and change the line "enabled=true" to "enabled=false"?

**Comment by AlexIIL** [comment] 2015-07-26 14:10
I might have got the path slightly wrong though, I didn't copy-paste it.

**Comment by Xiaminou** [comment] 2015-07-26 17:16
It works after disabling splash screen.

**Comment by AlexIIL** [comment] 2015-07-26 17:18
Oh good. Next week I'll propably make it properly disable forges loading screen.

**Comment by AlexIIL** [comment] 2015-07-26 19:18
(Closing this as I think it's done, open a new one if you disagree)

**Closed by AlexIIL** 2015-07-26 19:18 UTC

**Comment by maxsize213** [comment] 2018-10-28 02:48
This happened with mods. I had removed the cause; it still crashes. Additionally it was SkyFactory3. Logs: (to load it, use Microsoft Word and then download this: https://github.com/maxsize213/Crash-B =) ) Bye!

**Comment by AlexIIL** [comment] 2018-10-28 13:15
Can you try renaming "config/splash.properties" to "config/splash.properties.old"? (It looks like forge's own loading screen tries to find a resource that doesn't exist, rather than custom loading screen).

(Just FYI you should be able to open either files with notepad anyway)

**Comment by AlexIIL** [comment] 2018-10-28 13:17
Hang on, how did you find this issue? I haven't released any versions of custom loading screen or better loading screen for 1.10.2...
